# *** -----------------------------------------LINEAR ARRAY------------------------------------- ***

# **PRACTICE rough**

In [ ]:
#Create array
#1
import numpy as np
a = np.array([10, 20, 30, 40])
print(a)
print(type(a))
#2
b = np.zeros(5)
print(b)
print(type(b))
#3
c=[0]*5
arr=np.array(c)                         #list of len=5 with 0
print(arr)
print(type(arr))
#4
b = np.zeros(5, dtype=int)
print(b)
print(type(b))

[10 20 30 40]
<class 'numpy.ndarray'>
[0. 0. 0. 0. 0.]
<class 'numpy.ndarray'>
[0 0 0 0 0]
<class 'numpy.ndarray'>
[0 0 0 0 0]
<class 'numpy.ndarray'>


In [ ]:
#Add value without append
#                                              process1
import numpy as np
a = np.array([10, 20, 30, 40])
b = np.zeros(5,dtype=int)
for i in range(len(a)):
    b[i] = a[i]
b[len(a)] = 50  #because a er len b theke 1 kom
a=b
print(a)
#                                              process2
import numpy as np
a = np.array([10, 20, 30, 40])
b = np.zeros(len(a) + 1, dtype=int)
for i in range(len(a)):
    b[i] = a[i]
b[len(b)-1] = 50         #last index
a = b
print(a)

[10 20 30 40 50]
[10 20 30 40 50]


In [ ]:
#Iteration
import numpy as np
arr1 = np.array([1, 2, 3, 4])
for i in arr1:             #2      for i in range(0, len(arr1)):
  print(i)                 #         print(arr1[i])
print("................................................")

#reverse print
for i in range(len(arr1)-1,-1,-1):
  print(arr1[i])
print("................................................")

#while loop for reverse
i=0
while i<=len(arr1)-1:
  print(arr1[i])
  i=i+1
print("................................................")

#while loop for reverse
i=len(arr1)-1
while i>=0:
  print(arr1[i])
  i=i-1
print("................................................")



1
2
3
4
................................................
4
3
2
1
................................................
1
2
3
4
................................................
4
3
2
1
................................................


In [ ]:
#Copy(pass by reference)
arr1= np.array([1,2,3,4])
arr2= arr1
print(id(arr1)) #id() function is used to find the memory location
print(id(arr2))
print("................................................")
#Copy(pass by value)
def copyArray(arr):
  arr2= np.array([0]* len(arr))
  for i in range(len(arr)):
    arr2[i]= arr[i]
  return arr2
arr1= np.array([1,2,3,4])
arr2= copyArray(arr1)
# arr2= arr1.copy()
print(id(arr1))
print(id(arr2))

135696074412784
135696074412784
................................................
135696074415664
135696074416240


In [ ]:
#Resize
import numpy as np
def resizeArray(arr, new_size):
  arr2= np.array([0]* new_size)             #it can be None also
  for i in range(len(arr)):
    arr2[i]= arr[i]
  return arr2
arr1= np.array([1,2,3,4])
print(resizeArray(arr1, 6))

[1 2 3 4 0 0]


In [ ]:
#                                                                            Reverse

#                                                     Out of place( copy er moto new arr create kore)
#1
def reverse_out_of_place(arr):
  arr2= np.zeros(len(arr), dtype=int)
  i= 0
  while(i<=len(arr)-1):
    arr2[i]= arr[len(arr)-1-i]
    i+=1
  return arr2
arr= np.array([1,2,3,4,5])
print(reverse_out_of_place(arr))

#2
def reverse_out_of_place(arr):
  revarr= np.zeros(len(arr), dtype=int)
  i= 0
  j= len(arr)-1
  while(i<len(arr)):
    revarr[i] = arr[j]
    i+=1
    j-=1
  return revarr

#                                            Inplace( new create na kore old array tei sob reverse kora swap kore)

#for(1)
def reverse_in_place(arr):
  x= 0
  j= len(arr)-1
  for i in range(len(arr)//2):
    temp= arr[i]
    arr[i]=arr[j]           #SWAPING
    arr[j]=temp             #SWAPING
    j-=1
  return arr
arr= np.array([1,2,3,4,5])
print(reverse_in_place(arr))

#2
def reverse_in_place(arr):
  x, j = 0, len(arr)-1
  for i in range(len(arr)//2):
    arr[i], arr[j]= arr[j], arr[i]
    j-=1          # x+=0
  return arr

#while
def reverse_in_place(arr):
  i= 0
  j= len(arr)-1
  while i<j:
    temp= arr[i]
    arr[i]=arr[j]
    arr[j]=temp
    i+=1
    j-=1
  return arr

[5 4 3 2 1]
[5 4 3 2 1]


In [ ]:
#                                                                        SHIFTING LEFT
#                                                      *FOR 1 SLOT
#1
def shiftLeft(arr):
  for i in range(1,len(arr)):
    arr[i-1]= arr[i]
  arr[len(arr)-1]= 0           #None
  return arr
arr= np.array([1,2,3,4])
print(shiftLeft(arr))

#2
def shiftLeft(arr):
  for i in range(len(arr)-1):
    arr[i]= arr[i+1]
  arr[len(arr)-1]= 0         #None
  return arr

'''                                                      *FOR 1 OR MORE SLOT(K er jaigai joto ghor shift bolbe toto)
def shiftLeft(arr):
  for i in range(len(arr)-k):
    arr[i]= arr[i+k]
    arr[i+k]= 0           #None
  return arr                                   '''

[2 3 4 0]


In [ ]:
#                                                                         SHIFTING RIGHT
#                                                  for 1 slot
def shiftRight(arr):
  for i in range(len(arr)-1, 0, -1):
    arr[i]= arr[i-1]
    arr[i-1]=0
  #arr[0]=0
  return arr

#                                                  for 1 or more slot (first and last line bade sob 1 er jaigai joto ghor toto)
def shiftRight(arr):
  j=len(arr)-1
  for i in range(len(arr)-1):
    arr[j]= arr[j-1]
    arr[j-1]=0
    j-=1
  return arr
arr= np.array([1,2,3,4])
print(shiftRight(arr))

[0 1 2 3]


In [ ]:
#                                                                         ROTATE LEFT
# only for 1 ghor
def rotateLeft(arr):
  temp= arr[0]
  for i in range(1, len(arr), 1):
    arr[i-1]= arr[i]
  arr[len(arr)-1]= temp
  return arr
arr= np.array([1,2,3,4])
print(rotateLeft(arr))

[2 3 4 1]


In [ ]:
#                                                                         ROTATE RIGHT
#only for 1 ghor
def rotateRight(arr):
  temp= arr[len(arr)-1]
  for i in range(len(arr)-1, 0, -1):
    arr[i]= arr[i-1]
  arr[0]= temp
  return arr
arr= np.array([1,2,3,4])
print(rotateRight(arr))

# 1+ ghor hole  (ex=2  ; 2 er jaigai jotoghor toto change)
import numpy as np
def rotateRight(arr):
    temp = np.zeros(2)                                           # for storing 50, 60
    for i in range(len(arr)-2, len(arr)):
        temp[i-(len(arr)-2)] = arr[i]
    b = len(arr)-1                                           # starting index for right shift
    for j in range(len(arr)-3, -1, -1):
        arr[b] = arr[j]
        b -= 1
    for k in range(len(temp)):
        arr[k] = temp[k]
    return arr

arr = np.array([10, 20, 30, 40, 50, 60])
print(rotateRight(arr))




[4 1 2 3]


In [ ]:
#                                                                   Inserting at the end
def insert_at_the_end(arr, size, elem):
  if size >= len(arr):
    arr= resizeArray(arr, len(arr)+5)
  arr[size]= elem
  return arr
arr= np.zeros(4, dtype=int)
arr[0], arr[1], arr[2] = 4, 6, 5
print(arr)
print(insert_at_the_end(arr, 3, 15))

##                                                                     Inserting anywhere
def insert_anywhere(arr, size, index, elem):
  if index<0 or index>size:
    return "Insertion Not Possible"
  else:
    for i in range(size, index, -1): #Right Shift
      arr[i]= arr[i-1]
    arr[index]= elem
    return arr

arr= np.zeros(4, dtype=int)
arr[0], arr[1], arr[2] = 4, 6, 5
print(arr)
print(insert_anywhere(arr, 3, 1, 15))


[4 6 5 0]
[ 4  6  5 15]
[4 6 5 0]
[ 4 15  6  5]


In [ ]:
#Deleting any element
def delete_any_element (arr, size, index):
  if size == 0 or (index<0 and index>=size):
    return "Deletion Not Possible"
  for i in range(index, size, 1):
    arr[i]=arr[i+1]
    arr[size-1]=0
  return arr
arr= np.zeros(5, dtype=int)
arr[0], arr[1], arr[2], arr[3] = 4, 6, 5, 2
print(arr)
print(delete_any_element(arr, 4, 0)) #array, size, index

[4 6 5 2 0]
[6 5 0 0 0]


# **Practice sheet**